#############################################################################
# Makefile for building: testRadio
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  radio.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile radio.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_SSL -D__HAVE_SDRPLAY_V2__ -D__HAVE_RTLSDR__ -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -Isrc/ofdm-handling -Isrc/support -Isrc/support/viterbi-spiral -Isrc/support/protection -Isrc/backend -Isrc/backend/audio -Isrc/backend/data -Isrc/audio-sink -Idevices -Ihttpserver -Idevices/sdrplay-handler -Idevices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I. -I/../lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = testRadio1.0.0
DISTDIR = /home/jan/webradio/.tmp/testRadio1.0.0
LINK          = g++
LFLAGS        = -g -Wl,-O1
LIBS          = $(SUBLIBS) -lfftw3f -lfaad -lsamplerate -lportaudio -lusb-1.0 -ldl /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/radio-interface.cpp \
		src/html-writer.cpp \
		main.cpp \
		src/support/dab-params.cpp \
		src/support/dab-tables.cpp \
		src/support/fft-handler.cpp \
		src/support/charsets.cpp \
		src/support/band-handler.cpp \
		src/support/viterbi-spiral/spiral-no-sse.c \
		src/support/viterbi-spiral/viterbi-spiral.cpp \
		src/support/protection/protTables.cpp \
		src/support/protection/protection.cpp \
		src/support/protection/eep-protection.cpp \
		src/support/protection/uep-protection.cpp \
		src/ofdm-handling/dab-processor.cpp \
		src/ofdm-handling/fib-decoder.cpp \
		src/ofdm-handling/fic-handler.cpp \
		src/ofdm-handling/freq-interleaver.cpp \
		src/ofdm-handling/ofdm-decoder.cpp \
		src/ofdm-handling/phasereference.cpp \
		src/ofdm-handling/phasetable.cpp \
		src/ofdm-handling/sample-reader.cpp \
		src/ofdm-handling/timesyncer.cpp \
		src/backend/backend.cpp \
		src/backend/backend-driver.cpp \
		src/backend/backend-deconvolver.cpp \
		src/backend/firecode-checker.cpp \
		src/backend/galois.cpp \
		src/backend/reed-solomon.cpp \
		src/backend/msc-handler.cpp \
		src/backend/audio/mp2processor.cpp \
		src/backend/audio/mp4processor.cpp \
		src/backend/audio/faad-decoder.cpp \
		src/backend/data/pad-handler.cpp \
		src/audio-sink/audio-base.cpp \
		src/audio-sink/audiosink.cpp \
		src/audio-sink/newconverter.cpp \
		devices/device-handler.cpp \
		httpserver/httpconnectionhandler.cpp \
		httpserver/httpconnectionhandlerpool.cpp \
		httpserver/httpcookie.cpp \
		httpserver/httplistener.cpp \
		httpserver/httprequest.cpp \
		httpserver/httprequesthandler.cpp \
		httpserver/httpresponse.cpp \
		httpserver/httpsession.cpp \
		httpserver/httpsessionstore.cpp \
		devices/sdrplay-handler/sdrplay-handler.cpp \
		devices/rtlsdr-handler/rtlsdr-handler.cpp moc_radio-interface.cpp \
		moc_dab-processor.cpp \
		moc_fib-decoder.cpp \
		moc_fic-handler.cpp \
		moc_ofdm-decoder.cpp \
		moc_phasereference.cpp \
		moc_sample-reader.cpp \
		moc_mp2processor.cpp \
		moc_mp4processor.cpp \
		moc_faad-decoder.cpp \
		moc_pad-handler.cpp \
		moc_httpconnectionhandler.cpp \
		moc_httpconnectionhandlerpool.cpp \
		moc_httplistener.cpp \
		moc_httprequesthandler.cpp \
		moc_httpsessionstore.cpp
OBJECTS       = radio-interface.o \
		html-writer.o \
		main.o \
		dab-params.o \
		dab-tables.o \
		fft-handler.o \
		charsets.o \
		band-handler.o \
		spiral-no-sse.o \
		viterbi-spiral.o \
		protTables.o \
		protection.o \
		eep-protection.o \
		uep-protection.o \
		dab-processor.o \
		fib-decoder.o \
		fic-handler.o \
		freq-interleaver.o \
		ofdm-decoder.o \
		phasereference.o \
		phasetable.o \
		sample-reader.o \
		timesyncer.o \
		backend.o \
		backend-driver.o \
		backend-deconvolver.o \
		firecode-checker.o \
		galois.o \
		reed-solomon.o \
		msc-handler.o \
		mp2processor.o \
		mp4processor.o \
		faad-decoder.o \
		pad-handler.o \
		audio-base.o \
		audiosink.o \
		newconverter.o \
		device-handler.o \
		httpconnectionhandler.o \
		httpconnectionhandlerpool.o \
		httpcookie.o \
		httplistener.o \
		httprequest.o \
		httprequesthandler.o \
		httpresponse.o \
		httpsession.o \
		httpsessionstore.o \
		sdrplay-handler.o \
		rtlsdr-handler.o \
		moc_radio-interface.o \
		moc_dab-processor.o \
		moc_fib-decoder.o \
		moc_fic-handler.o \
		moc_ofdm-decoder.o \
		moc_phasereference.o \
		moc_sample-reader.o \
		moc_mp2processor.o \
		moc_mp4processor.o \
		moc_faad-decoder.o \
		moc_pad-handler.o \
		moc_httpconnectionhandler.o \
		moc_httpconnectionhandlerpool.o \
		moc_httplistener.o \
		moc_httprequesthandler.o \
		moc_httpsessionstore.o
DIST          = /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		radio.pro src/radio-interface.h \
		src/html-writer.h \
		src/support/dab-constants.h \
		src/support/dab-params.h \
		src/support/dab-tables.h \
		src/support/fft-handler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/support/charsets.h \
		src/support/band-handler.h \
		src/support/viterbi-spiral/spiral-no-sse.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/protection/protTables.h \
		src/support/protection/protection.h \
		src/support/protection/eep-protection.h \
		src/support/protection/uep-protection.h \
		src/ofdm-handling/dab-config.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/fib-table.h \
		src/ofdm-handling/fic-handler.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/phasereference.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/sample-reader.h \
		src/ofdm-handling/timesyncer.h \
		src/backend/backend.h \
		src/backend/backend-driver.h \
		src/backend/backend-deconvolver.h \
		src/backend/firecode-checker.h \
		src/backend/frame-processor.h \
		src/backend/galois.h \
		src/backend/mm_malloc.h \
		src/backend/reed-solomon.h \
		src/backend/msc-handler.h \
		src/backend/audio/mp2processor.h \
		src/backend/audio/mp4processor.h \
		src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h \
		src/backend/data/pad-handler.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/newconverter.h \
		devices/device-handler.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httpconnectionhandlerpool.h \
		httpserver/httpcookie.h \
		httpserver/httplistener.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpsession.h \
		httpserver/httpsessionstore.h \
		devices/sdrplay-handler/sdrplay-handler.h \
		devices/rtlsdr-handler/rtlsdr-handler.h src/radio-interface.cpp \
		src/html-writer.cpp \
		main.cpp \
		src/support/dab-params.cpp \
		src/support/dab-tables.cpp \
		src/support/fft-handler.cpp \
		src/support/charsets.cpp \
		src/support/band-handler.cpp \
		src/support/viterbi-spiral/spiral-no-sse.c \
		src/support/viterbi-spiral/viterbi-spiral.cpp \
		src/support/protection/protTables.cpp \
		src/support/protection/protection.cpp \
		src/support/protection/eep-protection.cpp \
		src/support/protection/uep-protection.cpp \
		src/ofdm-handling/dab-processor.cpp \
		src/ofdm-handling/fib-decoder.cpp \
		src/ofdm-handling/fic-handler.cpp \
		src/ofdm-handling/freq-interleaver.cpp \
		src/ofdm-handling/ofdm-decoder.cpp \
		src/ofdm-handling/phasereference.cpp \
		src/ofdm-handling/phasetable.cpp \
		src/ofdm-handling/sample-reader.cpp \
		src/ofdm-handling/timesyncer.cpp \
		src/backend/backend.cpp \
		src/backend/backend-driver.cpp \
		src/backend/backend-deconvolver.cpp \
		src/backend/firecode-checker.cpp \
		src/backend/galois.cpp \
		src/backend/reed-solomon.cpp \
		src/backend/msc-handler.cpp \
		src/backend/audio/mp2processor.cpp \
		src/backend/audio/mp4processor.cpp \
		src/backend/audio/faad-decoder.cpp \
		src/backend/data/pad-handler.cpp \
		src/audio-sink/audio-base.cpp \
		src/audio-sink/audiosink.cpp \
		src/audio-sink/newconverter.cpp \
		devices/device-handler.cpp \
		httpserver/httpconnectionhandler.cpp \
		httpserver/httpconnectionhandlerpool.cpp \
		httpserver/httpcookie.cpp \
		httpserver/httplistener.cpp \
		httpserver/httprequest.cpp \
		httpserver/httprequesthandler.cpp \
		httpserver/httpresponse.cpp \
		httpserver/httpsession.cpp \
		httpserver/httpsessionstore.cpp \
		devices/sdrplay-handler/sdrplay-handler.cpp \
		devices/rtlsdr-handler/rtlsdr-handler.cpp
QMAKE_TARGET  = testRadio
DESTDIR       = 
TARGET        = testRadio


first: all
####### Build rules

testRadio:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: radio.pro /../lib64/qt5/mkspecs/linux-g++/qmake.conf /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/opengl.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		radio.pro
	$(QMAKE) -o Makefile radio.pro
/../lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/../lib64/qt5/mkspecs/qconfig.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/../lib64/qt5/mkspecs/features/qt_functions.prf:
/../lib64/qt5/mkspecs/features/qt_config.prf:
/../lib64/qt5/mkspecs/linux-g++/qmake.conf:
/../lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/../lib64/qt5/mkspecs/features/exclusive_builds.prf:
/../lib64/qt5/mkspecs/features/toolchain.prf:
/../lib64/qt5/mkspecs/features/default_pre.prf:
/../lib64/qt5/mkspecs/features/resolve_config.prf:
/../lib64/qt5/mkspecs/features/default_post.prf:
/../lib64/qt5/mkspecs/features/warn_on.prf:
/../lib64/qt5/mkspecs/features/qt.prf:
/../lib64/qt5/mkspecs/features/resources_functions.prf:
/../lib64/qt5/mkspecs/features/resources.prf:
/../lib64/qt5/mkspecs/features/moc.prf:
/../lib64/qt5/mkspecs/features/unix/opengl.prf:
/../lib64/qt5/mkspecs/features/unix/thread.prf:
/../lib64/qt5/mkspecs/features/qmake_use.prf:
/../lib64/qt5/mkspecs/features/file_copies.prf:
/../lib64/qt5/mkspecs/features/testcase_targets.prf:
/../lib64/qt5/mkspecs/features/exceptions.prf:
/../lib64/qt5/mkspecs/features/yacc.prf:
/../lib64/qt5/mkspecs/features/lex.prf:
radio.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile radio.pro

qmake_all: FORCE


all: Makefile testRadio

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/radio-interface.h src/html-writer.h src/support/dab-constants.h src/support/dab-params.h src/support/dab-tables.h src/support/fft-handler.h src/support/process-params.h src/support/ringbuffer.h src/support/charsets.h src/support/band-handler.h src/support/viterbi-spiral/spiral-no-sse.h src/support/viterbi-spiral/viterbi-spiral.h src/support/protection/protTables.h src/support/protection/protection.h src/support/protection/eep-protection.h src/support/protection/uep-protection.h src/ofdm-handling/dab-config.h src/ofdm-handling/dab-processor.h src/ofdm-handling/fib-decoder.h src/ofdm-handling/fib-table.h src/ofdm-handling/fic-handler.h src/ofdm-handling/freq-interleaver.h src/ofdm-handling/ofdm-decoder.h src/ofdm-handling/phasereference.h src/ofdm-handling/phasetable.h src/ofdm-handling/sample-reader.h src/ofdm-handling/timesyncer.h src/backend/backend.h src/backend/backend-driver.h src/backend/backend-deconvolver.h src/backend/firecode-checker.h src/backend/frame-processor.h src/backend/galois.h src/backend/mm_malloc.h src/backend/reed-solomon.h src/backend/msc-handler.h src/backend/audio/mp2processor.h src/backend/audio/mp4processor.h src/backend/audio/faad-decoder.h src/backend/audio/neaacdec.h src/backend/data/pad-handler.h src/audio-sink/audio-base.h src/audio-sink/audiosink.h src/audio-sink/newconverter.h devices/device-handler.h httpserver/httpconnectionhandler.h httpserver/httpconnectionhandlerpool.h httpserver/httpcookie.h httpserver/httplistener.h httpserver/httprequest.h httpserver/httprequesthandler.h httpserver/httpresponse.h httpserver/httpsession.h httpserver/httpsessionstore.h devices/sdrplay-handler/sdrplay-handler.h devices/rtlsdr-handler/rtlsdr-handler.h $(DISTDIR)/
	$(COPY_FILE) --parents src/radio-interface.cpp src/html-writer.cpp main.cpp src/support/dab-params.cpp src/support/dab-tables.cpp src/support/fft-handler.cpp src/support/charsets.cpp src/support/band-handler.cpp src/support/viterbi-spiral/spiral-no-sse.c src/support/viterbi-spiral/viterbi-spiral.cpp src/support/protection/protTables.cpp src/support/protection/protection.cpp src/support/protection/eep-protection.cpp src/support/protection/uep-protection.cpp src/ofdm-handling/dab-processor.cpp src/ofdm-handling/fib-decoder.cpp src/ofdm-handling/fic-handler.cpp src/ofdm-handling/freq-interleaver.cpp src/ofdm-handling/ofdm-decoder.cpp src/ofdm-handling/phasereference.cpp src/ofdm-handling/phasetable.cpp src/ofdm-handling/sample-reader.cpp src/ofdm-handling/timesyncer.cpp src/backend/backend.cpp src/backend/backend-driver.cpp src/backend/backend-deconvolver.cpp src/backend/firecode-checker.cpp src/backend/galois.cpp src/backend/reed-solomon.cpp src/backend/msc-handler.cpp src/backend/audio/mp2processor.cpp src/backend/audio/mp4processor.cpp src/backend/audio/faad-decoder.cpp src/backend/data/pad-handler.cpp src/audio-sink/audio-base.cpp src/audio-sink/audiosink.cpp src/audio-sink/newconverter.cpp devices/device-handler.cpp httpserver/httpconnectionhandler.cpp httpserver/httpconnectionhandlerpool.cpp httpserver/httpcookie.cpp httpserver/httplistener.cpp httpserver/httprequest.cpp httpserver/httprequesthandler.cpp httpserver/httpresponse.cpp httpserver/httpsession.cpp httpserver/httpsessionstore.cpp devices/sdrplay-handler/sdrplay-handler.cpp devices/rtlsdr-handler/rtlsdr-handler.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -O2 -Wall -Wextra -dM -E -o moc_predefs.h /../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_radio-interface.cpp moc_dab-processor.cpp moc_fib-decoder.cpp moc_fic-handler.cpp moc_ofdm-decoder.cpp moc_phasereference.cpp moc_sample-reader.cpp moc_mp2processor.cpp moc_mp4processor.cpp moc_faad-decoder.cpp moc_pad-handler.cpp moc_httpconnectionhandler.cpp moc_httpconnectionhandlerpool.cpp moc_httplistener.cpp moc_httprequesthandler.cpp moc_httpsessionstore.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_radio-interface.cpp moc_dab-processor.cpp moc_fib-decoder.cpp moc_fic-handler.cpp moc_ofdm-decoder.cpp moc_phasereference.cpp moc_sample-reader.cpp moc_mp2processor.cpp moc_mp4processor.cpp moc_faad-decoder.cpp moc_pad-handler.cpp moc_httpconnectionhandler.cpp moc_httpconnectionhandlerpool.cpp moc_httplistener.cpp moc_httprequesthandler.cpp moc_httpsessionstore.cpp
moc_radio-interface.cpp: src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/radio-interface.h -o moc_radio-interface.cpp

moc_dab-processor.cpp: src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/support/process-params.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/dab-processor.h -o moc_dab-processor.cpp

moc_fib-decoder.cpp: src/ofdm-handling/fib-decoder.h \
		src/support/dab-constants.h \
		src/ofdm-handling/dab-config.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/fib-decoder.h -o moc_fib-decoder.cpp

moc_fic-handler.cpp: src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/dab-constants.h \
		src/support/dab-params.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/fic-handler.h -o moc_fic-handler.cpp

moc_ofdm-decoder.cpp: src/ofdm-handling/ofdm-decoder.h \
		src/support/dab-constants.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/freq-interleaver.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/ofdm-decoder.h -o moc_ofdm-decoder.cpp

moc_phasereference.cpp: src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-constants.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/phasereference.h -o moc_phasereference.cpp

moc_sample-reader.cpp: src/ofdm-handling/sample-reader.h \
		src/support/dab-constants.h \
		devices/device-handler.h \
		src/support/ringbuffer.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/ofdm-handling/sample-reader.h -o moc_sample-reader.cpp

moc_mp2processor.cpp: src/backend/audio/mp2processor.h \
		src/backend/frame-processor.h \
		src/support/ringbuffer.h \
		src/backend/data/pad-handler.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/backend/audio/mp2processor.h -o moc_mp2processor.cpp

moc_mp4processor.cpp: src/backend/audio/mp4processor.h \
		src/support/dab-constants.h \
		src/backend/frame-processor.h \
		src/backend/firecode-checker.h \
		src/backend/reed-solomon.h \
		src/backend/galois.h \
		src/backend/data/pad-handler.h \
		src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h \
		src/support/ringbuffer.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/backend/audio/mp4processor.h -o moc_mp4processor.cpp

moc_faad-decoder.cpp: src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h \
		src/support/ringbuffer.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/backend/audio/faad-decoder.h -o moc_faad-decoder.cpp

moc_pad-handler.cpp: src/backend/data/pad-handler.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include src/backend/data/pad-handler.h -o moc_pad-handler.cpp

moc_httpconnectionhandler.cpp: httpserver/httpconnectionhandler.h \
		httpserver/httpglobal.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include httpserver/httpconnectionhandler.h -o moc_httpconnectionhandler.cpp

moc_httpconnectionhandlerpool.cpp: httpserver/httpconnectionhandlerpool.h \
		httpserver/httpglobal.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include httpserver/httpconnectionhandlerpool.h -o moc_httpconnectionhandlerpool.cpp

moc_httplistener.cpp: httpserver/httplistener.h \
		httpserver/httpglobal.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httpconnectionhandlerpool.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include httpserver/httplistener.h -o moc_httplistener.cpp

moc_httprequesthandler.cpp: httpserver/httprequesthandler.h \
		httpserver/httpglobal.h \
		httpserver/httprequest.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include httpserver/httprequesthandler.h -o moc_httprequesthandler.cpp

moc_httpsessionstore.cpp: httpserver/httpsessionstore.h \
		httpserver/httpglobal.h \
		httpserver/httpsession.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequest.h \
		moc_predefs.h \
		/../lib64/qt5/bin/moc
	/../lib64/qt5/bin/moc $(DEFINES) --include /home/jan/webradio/moc_predefs.h -I/../lib64/qt5/mkspecs/linux-g++ -I/home/jan/webradio -I/home/jan/webradio -I/home/jan/webradio/src -I/home/jan/webradio/src/ofdm-handling -I/home/jan/webradio/src/support -I/home/jan/webradio/src/support/viterbi-spiral -I/home/jan/webradio/src/support/protection -I/home/jan/webradio/src/backend -I/home/jan/webradio/src/backend/audio -I/home/jan/webradio/src/backend/data -I/home/jan/webradio/src/audio-sink -I/home/jan/webradio/devices -I/home/jan/webradio/httpserver -I/home/jan/webradio/devices/sdrplay-handler -I/home/jan/webradio/devices/rtlsdr-handler -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include httpserver/httpsessionstore.h -o moc_httpsessionstore.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

radio-interface.o: src/radio-interface.cpp src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/html-writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radio-interface.o src/radio-interface.cpp

html-writer.o: src/html-writer.cpp src/html-writer.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o html-writer.o src/html-writer.cpp

main.o: main.cpp httpserver/httplistener.h \
		httpserver/httpglobal.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httpconnectionhandlerpool.h \
		devices/device-handler.h \
		devices/sdrplay-handler/sdrplay-handler.h \
		src/support/ringbuffer.h \
		devices/rtlsdr-handler/rtlsdr-handler.h \
		src/radio-interface.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dab-params.o: src/support/dab-params.cpp src/support/dab-params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dab-params.o src/support/dab-params.cpp

dab-tables.o: src/support/dab-tables.cpp src/support/dab-tables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dab-tables.o src/support/dab-tables.cpp

fft-handler.o: src/support/fft-handler.cpp src/support/fft-handler.h \
		src/support/dab-constants.h \
		src/support/dab-params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fft-handler.o src/support/fft-handler.cpp

charsets.o: src/support/charsets.cpp src/support/charsets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charsets.o src/support/charsets.cpp

band-handler.o: src/support/band-handler.cpp src/support/band-handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o band-handler.o src/support/band-handler.cpp

spiral-no-sse.o: src/support/viterbi-spiral/spiral-no-sse.c src/support/viterbi-spiral/spiral-no-sse.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o spiral-no-sse.o src/support/viterbi-spiral/spiral-no-sse.c

viterbi-spiral.o: src/support/viterbi-spiral/viterbi-spiral.cpp src/backend/mm_malloc.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/dab-constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viterbi-spiral.o src/support/viterbi-spiral/viterbi-spiral.cpp

protTables.o: src/support/protection/protTables.cpp src/support/protection/protTables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protTables.o src/support/protection/protTables.cpp

protection.o: src/support/protection/protection.cpp src/support/protection/protection.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/dab-constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protection.o src/support/protection/protection.cpp

eep-protection.o: src/support/protection/eep-protection.cpp src/support/dab-constants.h \
		src/support/protection/eep-protection.h \
		src/support/protection/protection.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/protection/protTables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eep-protection.o src/support/protection/eep-protection.cpp

uep-protection.o: src/support/protection/uep-protection.cpp src/support/dab-constants.h \
		src/support/protection/uep-protection.h \
		src/support/protection/protection.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/protection/protTables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uep-protection.o src/support/protection/uep-protection.cpp

dab-processor.o: src/ofdm-handling/dab-processor.cpp src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/support/process-params.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/ofdm-handling/timesyncer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dab-processor.o src/ofdm-handling/dab-processor.cpp

fib-decoder.o: src/ofdm-handling/fib-decoder.cpp src/ofdm-handling/fib-decoder.h \
		src/support/dab-constants.h \
		src/ofdm-handling/dab-config.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/charsets.h \
		src/ofdm-handling/fib-table.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fib-decoder.o src/ofdm-handling/fib-decoder.cpp

fic-handler.o: src/ofdm-handling/fic-handler.cpp src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/dab-constants.h \
		src/support/dab-params.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/protTables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fic-handler.o src/ofdm-handling/fic-handler.cpp

freq-interleaver.o: src/ofdm-handling/freq-interleaver.cpp src/ofdm-handling/freq-interleaver.h \
		src/support/dab-constants.h \
		src/support/dab-params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o freq-interleaver.o src/ofdm-handling/freq-interleaver.cpp

ofdm-decoder.o: src/ofdm-handling/ofdm-decoder.cpp src/ofdm-handling/ofdm-decoder.h \
		src/support/dab-constants.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/freq-interleaver.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ofdm-decoder.o src/ofdm-handling/ofdm-decoder.cpp

phasereference.o: src/ofdm-handling/phasereference.cpp src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-constants.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phasereference.o src/ofdm-handling/phasereference.cpp

phasetable.o: src/ofdm-handling/phasetable.cpp src/ofdm-handling/phasetable.h \
		src/support/dab-constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phasetable.o src/ofdm-handling/phasetable.cpp

sample-reader.o: src/ofdm-handling/sample-reader.cpp src/ofdm-handling/sample-reader.h \
		src/support/dab-constants.h \
		devices/device-handler.h \
		src/support/ringbuffer.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sample-reader.o src/ofdm-handling/sample-reader.cpp

timesyncer.o: src/ofdm-handling/timesyncer.cpp src/ofdm-handling/timesyncer.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/support/ringbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timesyncer.o src/ofdm-handling/timesyncer.cpp

backend.o: src/backend/backend.cpp src/support/dab-constants.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/backend/backend.h \
		src/backend/backend-driver.h \
		src/backend/frame-processor.h \
		src/backend/backend-deconvolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend.o src/backend/backend.cpp

backend-driver.o: src/backend/backend-driver.cpp src/backend/backend-driver.h \
		src/support/dab-constants.h \
		src/backend/frame-processor.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/backend/audio/mp2processor.h \
		src/backend/data/pad-handler.h \
		src/backend/audio/mp4processor.h \
		src/backend/firecode-checker.h \
		src/backend/reed-solomon.h \
		src/backend/galois.h \
		src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend-driver.o src/backend/backend-driver.cpp

backend-deconvolver.o: src/backend/backend-deconvolver.cpp src/backend/backend-deconvolver.h \
		src/support/dab-constants.h \
		src/support/protection/eep-protection.h \
		src/support/protection/protection.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/support/protection/uep-protection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backend-deconvolver.o src/backend/backend-deconvolver.cpp

firecode-checker.o: src/backend/firecode-checker.cpp src/backend/firecode-checker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o firecode-checker.o src/backend/firecode-checker.cpp

galois.o: src/backend/galois.cpp src/backend/galois.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o galois.o src/backend/galois.cpp

reed-solomon.o: src/backend/reed-solomon.cpp src/backend/reed-solomon.h \
		src/backend/galois.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reed-solomon.o src/backend/reed-solomon.cpp

msc-handler.o: src/backend/msc-handler.cpp src/support/dab-constants.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/backend/backend.h \
		src/backend/backend-driver.h \
		src/backend/frame-processor.h \
		src/backend/backend-deconvolver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o msc-handler.o src/backend/msc-handler.cpp

mp2processor.o: src/backend/audio/mp2processor.cpp src/backend/audio/mp2processor.h \
		src/backend/frame-processor.h \
		src/support/ringbuffer.h \
		src/backend/data/pad-handler.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp2processor.o src/backend/audio/mp2processor.cpp

mp4processor.o: src/backend/audio/mp4processor.cpp src/backend/audio/mp4processor.h \
		src/support/dab-constants.h \
		src/backend/frame-processor.h \
		src/backend/firecode-checker.h \
		src/backend/reed-solomon.h \
		src/backend/galois.h \
		src/backend/data/pad-handler.h \
		src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h \
		src/support/ringbuffer.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/charsets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mp4processor.o src/backend/audio/mp4processor.cpp

faad-decoder.o: src/backend/audio/faad-decoder.cpp src/backend/audio/faad-decoder.h \
		src/backend/audio/neaacdec.h \
		src/support/ringbuffer.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faad-decoder.o src/backend/audio/faad-decoder.cpp

pad-handler.o: src/backend/data/pad-handler.cpp src/backend/data/pad-handler.h \
		src/radio-interface.h \
		httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequesthandler.h \
		src/support/process-params.h \
		src/support/ringbuffer.h \
		src/ofdm-handling/dab-processor.h \
		src/support/dab-constants.h \
		src/ofdm-handling/sample-reader.h \
		devices/device-handler.h \
		src/ofdm-handling/phasereference.h \
		src/support/fft-handler.h \
		src/support/dab-params.h \
		src/ofdm-handling/phasetable.h \
		src/ofdm-handling/ofdm-decoder.h \
		src/ofdm-handling/freq-interleaver.h \
		src/ofdm-handling/fic-handler.h \
		src/support/viterbi-spiral/viterbi-spiral.h \
		src/ofdm-handling/fib-decoder.h \
		src/ofdm-handling/dab-config.h \
		src/backend/msc-handler.h \
		src/support/band-handler.h \
		src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/charsets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pad-handler.o src/backend/data/pad-handler.cpp

audio-base.o: src/audio-sink/audio-base.cpp src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/ringbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audio-base.o src/audio-sink/audio-base.cpp

audiosink.o: src/audio-sink/audiosink.cpp src/audio-sink/audiosink.h \
		src/audio-sink/audio-base.h \
		src/audio-sink/newconverter.h \
		src/support/ringbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audiosink.o src/audio-sink/audiosink.cpp

newconverter.o: src/audio-sink/newconverter.cpp src/audio-sink/newconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newconverter.o src/audio-sink/newconverter.cpp

device-handler.o: devices/device-handler.cpp devices/device-handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o device-handler.o devices/device-handler.cpp

httpconnectionhandler.o: httpserver/httpconnectionhandler.cpp httpserver/httpconnectionhandler.h \
		httpserver/httpglobal.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpconnectionhandler.o httpserver/httpconnectionhandler.cpp

httpconnectionhandlerpool.o: httpserver/httpconnectionhandlerpool.cpp httpserver/httpconnectionhandlerpool.h \
		httpserver/httpglobal.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpconnectionhandlerpool.o httpserver/httpconnectionhandlerpool.cpp

httpcookie.o: httpserver/httpcookie.cpp httpserver/httpcookie.h \
		httpserver/httpglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpcookie.o httpserver/httpcookie.cpp

httplistener.o: httpserver/httplistener.cpp httpserver/httplistener.h \
		httpserver/httpglobal.h \
		httpserver/httpconnectionhandler.h \
		httpserver/httprequest.h \
		httpserver/httprequesthandler.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httpconnectionhandlerpool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httplistener.o httpserver/httplistener.cpp

httprequest.o: httpserver/httprequest.cpp httpserver/httprequest.h \
		httpserver/httpglobal.h \
		httpserver/httpcookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httprequest.o httpserver/httprequest.cpp

httprequesthandler.o: httpserver/httprequesthandler.cpp httpserver/httprequesthandler.h \
		httpserver/httpglobal.h \
		httpserver/httprequest.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httprequesthandler.o httpserver/httprequesthandler.cpp

httpresponse.o: httpserver/httpresponse.cpp httpserver/httpresponse.h \
		httpserver/httpglobal.h \
		httpserver/httpcookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpresponse.o httpserver/httpresponse.cpp

httpsession.o: httpserver/httpsession.cpp httpserver/httpsession.h \
		httpserver/httpglobal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpsession.o httpserver/httpsession.cpp

httpsessionstore.o: httpserver/httpsessionstore.cpp httpserver/httpsessionstore.h \
		httpserver/httpglobal.h \
		httpserver/httpsession.h \
		httpserver/httpresponse.h \
		httpserver/httpcookie.h \
		httpserver/httprequest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpsessionstore.o httpserver/httpsessionstore.cpp

sdrplay-handler.o: devices/sdrplay-handler/sdrplay-handler.cpp devices/sdrplay-handler/sdrplay-handler.h \
		src/support/ringbuffer.h \
		devices/device-handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sdrplay-handler.o devices/sdrplay-handler/sdrplay-handler.cpp

rtlsdr-handler.o: devices/rtlsdr-handler/rtlsdr-handler.cpp devices/rtl-sdr.h \
		devices/rtl-sdr_export.h \
		devices/rtlsdr-handler/rtlsdr-handler.h \
		src/support/ringbuffer.h \
		devices/device-handler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtlsdr-handler.o devices/rtlsdr-handler/rtlsdr-handler.cpp

moc_radio-interface.o: moc_radio-interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radio-interface.o moc_radio-interface.cpp

moc_dab-processor.o: moc_dab-processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dab-processor.o moc_dab-processor.cpp

moc_fib-decoder.o: moc_fib-decoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fib-decoder.o moc_fib-decoder.cpp

moc_fic-handler.o: moc_fic-handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fic-handler.o moc_fic-handler.cpp

moc_ofdm-decoder.o: moc_ofdm-decoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ofdm-decoder.o moc_ofdm-decoder.cpp

moc_phasereference.o: moc_phasereference.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_phasereference.o moc_phasereference.cpp

moc_sample-reader.o: moc_sample-reader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sample-reader.o moc_sample-reader.cpp

moc_mp2processor.o: moc_mp2processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mp2processor.o moc_mp2processor.cpp

moc_mp4processor.o: moc_mp4processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mp4processor.o moc_mp4processor.cpp

moc_faad-decoder.o: moc_faad-decoder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_faad-decoder.o moc_faad-decoder.cpp

moc_pad-handler.o: moc_pad-handler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pad-handler.o moc_pad-handler.cpp

moc_httpconnectionhandler.o: moc_httpconnectionhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpconnectionhandler.o moc_httpconnectionhandler.cpp

moc_httpconnectionhandlerpool.o: moc_httpconnectionhandlerpool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpconnectionhandlerpool.o moc_httpconnectionhandlerpool.cpp

moc_httplistener.o: moc_httplistener.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httplistener.o moc_httplistener.cpp

moc_httprequesthandler.o: moc_httprequesthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httprequesthandler.o moc_httprequesthandler.cpp

moc_httpsessionstore.o: moc_httpsessionstore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpsessionstore.o moc_httpsessionstore.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

